apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault
  labels:
    type: local
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: vault-pvc
    namespace: vault-operator
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/vault/'